apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  labels:
    app: logtofile
    app.kubernetes.io/component: logtofile
    app.kubernetes.io/instance: logtofile
    manager: kube-controller-manager
    operation: Update
  name: logtofile
  namespace: user15-logging
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: logtofile
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: logtofile
    spec:
      containers:
      - image: quay.io/gpte-devops-automation/logtofile@sha256:bf1dfd99bfc4840132068c8b4551482792554f84d8b178a4fa1a72b1f31c7d4c
        imagePullPolicy: IfNotPresent
        name: logtofile
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      - image: docker.io/busybox:latest
        imagePullPolicy: IfNotPresent
        name: logtostdout
        command:
          - /bin/sh
          - -c
          - "tail -f /tmp/datelog.txt"
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emtpyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
