apiVersion: v1
imagePullSecrets:
- name: jenkins-dockercfg-8ffmj
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"jenkins"}}'
  creationTimestamp: "2020-12-02T13:33:25Z"
  labels:
    app: jenkins-persistent
    template: jenkins-persistent-template
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:openshift.io/generated-by: {}
          f:serviceaccounts.openshift.io/oauth-redirectreference.jenkins: {}
        f:labels:
          .: {}
          f:app: {}
          f:template: {}
    manager: oc
    operation: Update
    time: "2020-12-02T13:33:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:secrets:
        .: {}
        k:{"name":"jenkins-token-kswt5"}:
          .: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-12-02T13:33:26Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:imagePullSecrets: {}
      f:secrets:
        k:{"name":"jenkins-dockercfg-8ffmj"}:
          .: {}
          f:name: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2020-12-02T13:33:26Z"
  name: jenkins
  namespace: default
  resourceVersion: "7728678"
  selfLink: /api/v1/namespaces/default/serviceaccounts/jenkins
  uid: 284bd05e-70ab-41c3-b867-a46a18c0522d
secrets:
- name: jenkins-token-kswt5
- name: jenkins-dockercfg-8ffmj
