apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgresql-persistent
    app.kubernetes.io/component: postgresql-persistent
    app.kubernetes.io/instance: postgresql-persistent
    template: postgresql-persistent-template
  name: postgresql
  namespace: user15-sonarqube
  resourceVersion: "3362934"
data:
  database-name: c29uYXJkYg==
  database-password: c29uYXIxMjM0
  database-user: c29uYXI=
type: Opaque
