apiVersion: gpte.opentlc.com/v1alpha1
kind: Gogs
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gpte.opentlc.com/v1alpha1","kind":"Gogs","metadata":{"annotations":{},"name":"gogs","namespace":"user15-gogs"},"spec":{"gogsSsl":false,"gogsVolumeSize":"4Gi","postgresqlVolumeSize":"4Gi"}}
  creationTimestamp: "2020-12-01T13:14:00Z"
  generation: 2
  managedFields:
  - apiVersion: gpte.opentlc.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:gogsSsl: {}
        f:gogsVolumeSize: {}
        f:postgresqlVolumeSize: {}
    manager: oc
    operation: Update
    time: "2020-12-01T13:16:52Z"
  - apiVersion: gpte.opentlc.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:conditions: {}
    manager: ansible-operator
    operation: Update
    time: "2020-12-02T07:06:08Z"
  name: gogs
  namespace: user15-gogs
  resourceVersion: "2712283"
  selfLink: /apis/gpte.opentlc.com/v1alpha1/namespaces/user15-gogs/gogs/gogs
  uid: f13a17f0-8031-4898-ac16-a55da9cd21c0
spec:
  gogsSsl: false
  gogsVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
status:
  conditions:
  - ansibleResult:
      changed: 0
      completion: 2020-12-02T07:06:08.370909
      failures: 0
      ok: 8
      skipped: 0
    lastTransitionTime: "2020-12-01T13:14:00Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
