apiVersion: v1
data:
  password: cjNkaDR0MSE=
  username: dXNlcjE1
kind: Secret
metadata:
  creationTimestamp: "2020-12-03T09:18:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
        f:username: {}
      f:type: {}
    manager: oc
    operation: Update
    time: "2020-12-03T09:18:44Z"
  name: build-secret
  namespace: user15-builds
  resourceVersion: "4686311"
  selfLink: /api/v1/namespaces/user15-builds/secrets/build-secret
  uid: 0a355fea-378b-4b61-9e81-dc96c8ea3afd
type: Opaque
